apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: external-user
  labels:
    strimzi.io/cluster: routes-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-test-apps
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: kafka-test-apps
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: external-group
          patternType: literal
        operation: Read
        host: "*"
