apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: np-cluster
  namespace: kafka-np
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
    version: 2.8.0
    replicas: 2
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.8'
      inter.broker.protocol.version: '2.8'
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3

